#!/bin/sh

# this file makes a header file out of a binary file

BINFILENAME=$1

ARRAYNAME=$BINFILENAME
ARRAYNAME=${ARRAYNAME//-/_}
ARRAYNAME=${ARRAYNAME//./_}

echo "/* Autogenerated file, do not edit */"
echo "const unsigned char $ARRAYNAME[] = {"
hexdump -v -e '" " 16/1 "  0x%02x, " "\n"' $BINFILENAME | sed -e '$s/0x  ,//g'
echo "};"
